version: "3"

services:
  metabase:
    container_name: metabase
    image: metabase/metabase
    env_file: .env
    ports:
      - 3001:3000
    networks:
      - mysql-network
      - nginx_proxy_link
    environment:
      VIRTUAL_HOST: ${METABASE_DOMAIN_NAME}
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: ${METABASE_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
      SSL_POLICY: "Mozilla-Modern"
    volumes:
      - ./docker/volumes/metabase:/metabase.db:cached
  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/volumes/db/mysql_data:/var/lib/mysql
    networks:
      - mysql-network
  web:
    build:
      context: .
      args:
        WS_HOST: ${WS_HOST}
        WS_PORT: ${WS_PORT}
    restart: always
    env_file: .env
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      WS_HOST: ${WS_HOST}
      WS_PORT: ${WS_PORT}
      VIRTUAL_HOST: ${WEB_DOMAIN_NAME}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${WEB_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
      SSL_POLICY: "Mozilla-Modern"
    networks:
      - mysql-network
      - nginx_proxy_link
    ports:
      - 3000:3000
      - 5000:5000
      - 8000:8000

networks:
  mysql-network:
    driver: bridge
  nginx_proxy_link:
    external: true
